// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function AutoSelectBestNode() {
  return window['go']['main']['App']['AutoSelectBestNode']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetTraffic() {
  return window['go']['main']['App']['GetTraffic']();
}

export function RemoveSubscription(arg1) {
  return window['go']['main']['App']['RemoveSubscription'](arg1);
}

export function SelectNode(arg1) {
  return window['go']['main']['App']['SelectNode'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetCompactMode(arg1) {
  return window['go']['main']['App']['SetCompactMode'](arg1);
}

export function SetRuleMode(arg1) {
  return window['go']['main']['App']['SetRuleMode'](arg1);
}

export function SetSubscriptionRemark(arg1, arg2) {
  return window['go']['main']['App']['SetSubscriptionRemark'](arg1, arg2);
}

export function SetTunMode(arg1) {
  return window['go']['main']['App']['SetTunMode'](arg1);
}

export function ShouldStartCompact() {
  return window['go']['main']['App']['ShouldStartCompact']();
}

export function ToggleProxy() {
  return window['go']['main']['App']['ToggleProxy']();
}

export function UseSubscription(arg1) {
  return window['go']['main']['App']['UseSubscription'](arg1);
}
