// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function AddSubscription(arg1:string,arg2:string):Promise<Array<backend.Subscription>>;

export function AutoSelectBestNode():Promise<main.ProxyStatus>;

export function GetAutoStart():Promise<boolean>;

export function GetNodes():Promise<Array<backend.ProxyNode>>;

export function GetSettings():Promise<backend.AppSettings>;

export function GetStatus():Promise<main.ProxyStatus>;

export function GetSubscriptions():Promise<Array<backend.Subscription>>;

export function GetTraffic():Promise<main.TrafficInfo>;

export function RemoveSubscription(arg1:string):Promise<Array<backend.Subscription>>;

export function SelectNode(arg1:string):Promise<main.ProxyStatus>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetCompactMode(arg1:boolean):Promise<void>;

export function SetRuleMode(arg1:boolean):Promise<main.ProxyStatus>;

export function SetSubscriptionRemark(arg1:string,arg2:string):Promise<Array<backend.Subscription>>;

export function SetTunMode(arg1:boolean):Promise<main.ProxyStatus>;

export function ShouldStartCompact():Promise<boolean>;

export function ToggleProxy():Promise<main.ProxyStatus>;

export function UseSubscription(arg1:string):Promise<main.ProxyStatus>;
